import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { SmsPoster } from "@/components/sms-image";
import { useSmsStore, templateVariables, renderTemplate, countCredits, isValidPhone, type MsgType } from "@/lib/sms-store";
import { usePhoneCards } from "@/lib/phone-card-store";
import { sendReasons } from "@/lib/phone-cards";
import { CardPanel, CardField, ErrorNote } from "./card-common";
export function CardSendPanel({cardId,planId,onClose}:{cardId:string;planId?:string | undefined;onClose:()=>void}) {
  const {state,setState}=usePhoneCards();const sms=useSmsStore();const [targetId,setTargetId]=useState("");const [phone,setPhone]=useState("");const [region,setRegion]=useState("美国");const [type,setType]=useState<MsgType>("text");const [tplId,setTplId]=useState("");const [text,setText]=useState("");const [vars,setVars]=useState<Record<string,string>>({});const [follow,setFollow]=useState(true);const [error,setError]=useState("");const [done,setDone]=useState(false);
  const card=state.cards.find(c=>c.id===cardId);const plan=state.plans.find(p=>planId?p.id===planId:p.cardId===cardId&&p.active);const target=sms.targets.find(t=>t.id===targetId&&t.enabled);const tpl=sms.templates.find(t=>t.id===tplId&&t.enabled);
  const variables=tpl?templateVariables(tpl.content).filter(v=>v.token!=="{联系人}"||!target):[];
  const content=useMemo(()=>tpl?renderTemplate(tpl.content,target?.name??vars["{联系人}"]??"",vars):text,[tpl,target,vars,text]);
  if(!card)return null;
  function submit(){if(!card||!plan)return;const reasons=sendReasons(card,plan);if(reasons.length){setError(reasons.join("；"));return;}if(!isValidPhone(target?.phone??phone)){setError("请填写有效国际收件号码");return;}if(!content.trim()||variables.some(v=>!vars[v.token]?.trim())){setError("请填写内容及全部模板变量");return;}if(type==="image"&&(!tpl||!plan.image)){setError("图片短信需选择启用模板且通道支持图片");return;}if(follow&&plan.receive!==true){setError("当前套餐不支持回复接收，请取消跟进或更换卡");return;}if((target?.region??region)!==plan.region){setError("演示通道不支持该收件地区，请选择匹配的卡片");return;}const credits=countCredits(content,follow);if(credits>12480-sms.records.reduce((n,r)=>n+(r.status==="failed"?0:r.credits),0)){setError("积分余额不足");return;}
    sms.sendCardSms({target,phone:target?.phone??phone,region:target?.region??region,content,msgType:type,followUp:follow});setState(s=>({...s,plans:s.plans.map(p=>p.id===plan.id?{...p,used:p.used+1}:p),jobs:[{id:crypto.randomUUID(),at:new Date().toISOString(),type:"模拟发送短信",items:[{cardId:card.id,label:target?.phone??phone,state:"成功"}]},...s.jobs]}));setDone(true);
  }
  return <CardPanel title="发送短信 · 模拟" onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>{done?"关闭":"取消"}</Button>{!done&&<Button onClick={submit}>模拟发送 · {countCredits(content,follow)} 积分</Button>}</>}><p className="rounded-md bg-warning-soft p-3 text-xs text-warning-foreground">仅模拟发送并生成短信明细，不向真实号码发送。</p>{done?<p className="py-12 text-center font-semibold text-primary">模拟短信已提交，可在短信明细查看。</p>:<><div className="border-b border-border pb-4 text-sm"><p>{card.note} · {plan?.phone??"号码未回传"}</p><p className="mt-2 text-xs text-muted-foreground">{plan?.region} · {plan?.channel}</p></div><CardField label="选择启用目标"><select className="field" value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">直接输入收件号码</option>{sms.targets.filter(t=>t.enabled).map(t=><option key={t.id} value={t.id}>{t.name} · {t.phone}</option>)}</select></CardField>{!target&&<><CardField label="收件号码"><input aria-label="收件号码" className="field" placeholder="+12025550123" value={phone} onChange={e=>setPhone(e.target.value)}/></CardField><CardField label="目标地区"><input className="field" value={region} onChange={e=>setRegion(e.target.value)}/></CardField></>}<CardField label="发信内容类型"><select className="field" value={type} onChange={e=>setType(e.target.value==="image"?"image":"text")}><option value="text">文本</option><option value="image">图片</option></select></CardField><CardField label="短信模板"><select className="field" value={tplId} onChange={e=>{setTplId(e.target.value);setVars({});}}><option value="">直接输入文本</option>{sms.templates.filter(t=>t.enabled).map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></CardField>{variables.map(v=><CardField key={v.token} label={v.label}><input className="field" value={vars[v.token]??""} onChange={e=>setVars(p=>({...p,[v.token]:e.target.value}))}/></CardField>)}{!tpl&&<CardField label="短信内容"><textarea aria-label="短信内容" className="field min-h-32" value={text} onChange={e=>setText(e.target.value)}/></CardField>}{type==="image"&&tpl?<SmsPoster content={content}/>:tpl&&<p className="rounded-md bg-muted p-3 text-sm">{content}</p>}<label className="flex gap-2 text-sm"><Checkbox checked={follow} onCheckedChange={v=>setFollow(v===true)}/>是否跟进回复</label><p className="text-xs text-muted-foreground">预计积分 {countCredits(content,follow)} · 跟进为基础积分的 1.5 倍</p><ErrorNote text={error}/></>}</CardPanel>;
}