/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as Tasks2RouteImport } from './routes/tasks2'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as Tasks2TaskIdRouteImport } from './routes/tasks2_.$taskId'
import { Route as TasksTaskIdRouteImport } from './routes/tasks_.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const Tasks2Route = Tasks2RouteImport.update({
  id: '/tasks2',
  path: '/tasks2',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const Tasks2TaskIdRoute = Tasks2TaskIdRouteImport.update({
  id: '/tasks2_/$taskId',
  path: '/tasks2/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks_/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/targets': typeof TargetsRoute
  '/tasks': typeof TasksRoute
  '/tasks2': typeof Tasks2Route
  '/templates': typeof TemplatesRoute
  '/tasks2/$taskId': typeof Tasks2TaskIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/targets': typeof TargetsRoute
  '/tasks': typeof TasksRoute
  '/tasks2': typeof Tasks2Route
  '/templates': typeof TemplatesRoute
  '/tasks2/$taskId': typeof Tasks2TaskIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/targets': typeof TargetsRoute
  '/tasks': typeof TasksRoute
  '/tasks2': typeof Tasks2Route
  '/templates': typeof TemplatesRoute
  '/tasks2_/$taskId': typeof Tasks2TaskIdRoute
  '/tasks_/$taskId': typeof TasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/targets'
    | '/tasks'
    | '/tasks2'
    | '/templates'
    | '/tasks2/$taskId'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/targets'
    | '/tasks'
    | '/tasks2'
    | '/templates'
    | '/tasks2/$taskId'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/targets'
    | '/tasks'
    | '/tasks2'
    | '/templates'
    | '/tasks2_/$taskId'
    | '/tasks_/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  TargetsRoute: typeof TargetsRoute
  TasksRoute: typeof TasksRoute
  Tasks2Route: typeof Tasks2Route
  TemplatesRoute: typeof TemplatesRoute
  Tasks2TaskIdRoute: typeof Tasks2TaskIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks2': {
      id: '/tasks2'
      path: '/tasks2'
      fullPath: '/tasks2'
      preLoaderRoute: typeof Tasks2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks2_/$taskId': {
      id: '/tasks2_/$taskId'
      path: '/tasks2/$taskId'
      fullPath: '/tasks2/$taskId'
      preLoaderRoute: typeof Tasks2TaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks_/$taskId': {
      id: '/tasks_/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  TargetsRoute: TargetsRoute,
  TasksRoute: TasksRoute,
  Tasks2Route: Tasks2Route,
  TemplatesRoute: TemplatesRoute,
  Tasks2TaskIdRoute: Tasks2TaskIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
